version: "3"
services:
  api:
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      - redis
      - database
    networks:
      - app-network
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - atypikhouse-data:/var/lib/postgresql/data
    networks:
      - app-network
  nginx:
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - api_root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - api
    networks:
      - app-network
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - atypikhouse-redis:/data
    networks:
      - app-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - api_root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email dorosario.enzo@gmail.com --agree-tos -d api.atypikhou.se

volumes:
  atypikhouse-data:
  atypikhouse-redis:
  certbot-etc:
  certbot-var:
  api_root:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/api/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ubuntu/api/dhparam/
      o: bind

networks:
  app-network:
    driver: bridge
