version: "3"
services:
  api:
    build: .
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
    depends_on:
      - redis
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - atypikhouse-data:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
    volumes:
      - atypikhouse-redis:/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
volumes:
  atypikhouse-data:
  atypikhouse-redis:
