export enum DeleteReasons {
  UNKNOWN = "UNKNOWN",
  TC_NON_COMPLIANT = "TC_NON_COMPLIANT", // Non conforme aux CGU
  NOT_DISCLOSABLE = "NOT_DISCLOSABLE",
  STAFF_UNILATERAL = "STAFF_UNILATERAL",
  OWNER_UNILATERAL = "OWNER_UNILATERAL",
  DISPUTE = "DISPUTE",
}
