import {MigrationInterface, QueryRunner} from "typeorm";

export class FakeOffers1629667866873 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
insert into offer (id, title, description, latitude, longitude, status) values (1, 'ipsum primis in faucibus orci', 'Sed ante.', 38.0307786, 23.7038541, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (2, 'integer aliquet massa id lobortis convallis tortor', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 56.4987582, 38.1830715, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (3, 'viverra dapibus nulla suscipit ligula in', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 13.9142931, -87.921223, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (4, 'vel ipsum praesent blandit lacinia erat vestibulum', 'Proin interdum mauris non ligula pellentesque ultrices.', 51.7754831, 32.2595792, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (5, 'eget tempus vel pede morbi porttitor lorem id', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 12.4035699, 124.7689819, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (6, 'justo in blandit ultrices enim', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 34.341574, 108.93977, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (7, 'morbi odio odio elementum eu', 'Integer ac leo. Pellentesque ultrices mattis odio.', 46.6275321, 16.2176399, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (8, 'pede lobortis ligula sit amet', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 23.116912, 113.30928, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (9, 'ridiculus mus etiam vel augue', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', -9.7018, 120.4918, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (10, 'lobortis sapien sapien non mi', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 40.1578419, 44.0925766, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (11, 'donec pharetra magna vestibulum aliquet ultrices erat tortor', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 48.8579687, 2.5764306, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (12, 'proin at turpis a pede', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', 30.453667, 114.872199, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (13, 'cubilia curae mauris viverra diam', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.', -6.1989828, 106.5996595, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (14, 'ligula sit amet eleifend pede libero', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 8.1524286, -81.1802619, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (15, 'lacus at velit vivamus vel nulla', 'Suspendisse potenti. Nullam porttitor lacus at turpis.', 40.6307451, -74.1181234, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (16, 'libero convallis eget eleifend luctus ultricies eu', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 49.9776657, 20.9421091, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (17, 'mattis pulvinar nulla pede ullamcorper augue', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 33.044814, 106.656635, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (18, 'eros viverra eget congue eget', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.', 15.6883639, 120.6208167, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (19, 'morbi vel lectus in quam fringilla', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 60.7428382, 22.5352853, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (20, 'neque duis bibendum morbi non quam nec', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 21.0362368, 105.7905825, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (21, 'sodales scelerisque mauris sit amet', 'Donec dapibus. Duis at velit eu est congue elementum.', 34.40744, 70.63937, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (22, 'gravida sem praesent id massa id nisl', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 45.1253665, 42.0223291, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (23, 'sed vestibulum sit amet cursus', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 37.54, -77.45, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (24, 'odio porttitor id consequat in consequat ut nulla', 'Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', 53.9045398, 27.5615244, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (25, 'nulla dapibus dolor vel est donec odio', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 16.80778, 48.10917, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (26, 'justo pellentesque viverra pede ac diam', 'Etiam faucibus cursus urna. Ut tellus.', 43.6347968, 23.3663219, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (27, 'at velit vivamus vel nulla eget eros', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 50.3633974, 25.1107867, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (28, 'nunc rhoncus dui vel sem sed', 'Nam nulla.', -28.672732, 20.4284431, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (29, 'sed accumsan felis ut at dolor quis', 'Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 38.407753, 114.015532, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (30, 'purus eu magna vulputate luctus cum sociis', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 52.423387, 20.9739484, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (31, 'enim in tempor turpis nec euismod', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.', -15.813904, -43.3043938, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (32, 'in blandit ultrices enim lorem ipsum dolor', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 59.7414102, 10.2299413, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (33, 'tincidunt lacus at velit vivamus', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 12.3211354, 122.6736631, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (34, 'rutrum rutrum neque aenean auctor gravida sem praesent', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.', 50.772008, 22.956207, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (35, 'ornare imperdiet sapien urna pretium nisl', 'Maecenas ut massa quis augue luctus tincidunt.', 40.7316367, 20.0427329, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (36, 'augue vestibulum ante ipsum primis in faucibus', 'Proin at turpis a pede posuere nonummy. Integer non velit.', -26.5380045, -57.0421483, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (37, 'porta volutpat quam pede lobortis ligula sit amet', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', -20.8878921, 55.4247503, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (38, 'morbi ut odio cras mi pede', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', -4.1384805, 29.803397, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (39, 'vel nisl duis ac nibh fusce', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', -7.1520459, 108.5196028, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (40, 'parturient montes nascetur ridiculus mus', 'Nunc nisl.', 39.128291, 117.251586, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (41, 'dui vel nisl duis ac nibh', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 57.7194979, 11.9142911, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (42, 'quam sapien varius ut blandit', 'Curabitur in libero ut massa volutpat convallis.', -23.0931156, -46.9513691, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (43, 'ultrices posuere cubilia curae mauris viverra diam vitae', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', -18.4943258, -40.4657826, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (44, 'sit amet lobortis sapien sapien', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 13.420533, 123.41496, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (45, 'orci nullam molestie nibh in lectus', 'Morbi porttitor lorem id ligula.', 33.8462304, 35.9019775, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (46, 'neque sapien placerat ante nulla justo aliquam quis', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 13.8536285, -89.4535357, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (47, 'et commodo vulputate justo in blandit ultrices', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 42.891255, 129.508945, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (48, 'nunc commodo placerat praesent blandit', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.', 35.3255514, 25.2773184, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (49, 'integer a nibh in quis justo maecenas rhoncus', 'Pellentesque eget nunc.', 27.6376503, 30.8510692, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (50, 'morbi vel lectus in quam', 'Integer tincidunt ante vel ipsum.', 65.2958948, 21.3194467, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (51, 'sem fusce consequat nulla nisl', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', -13.8791041, -72.875917, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (52, 'blandit lacinia erat vestibulum sed magna', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 35.303704, 113.926763, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (53, 'luctus nec molestie sed justo', 'Nullam varius. Nulla facilisi.', 32.7778898, 61.6567273, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (54, 'volutpat erat quisque erat eros viverra eget', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.', 5.934363, -73.615679, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (55, 'consequat varius integer ac leo pellentesque ultrices mattis', 'Etiam faucibus cursus urna. Ut tellus.', 9.1192516, 4.8261424, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (56, 'id turpis integer aliquet massa id lobortis', 'Proin at turpis a pede posuere nonummy. Integer non velit.', -24.3965818, 25.4970466, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (57, 'sit amet nulla quisque arcu libero rutrum', 'Proin eu mi. Nulla ac enim.', 31.375657, 34.905759, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (58, 'nec molestie sed justo pellentesque viverra pede', 'In sagittis dui vel nisl. Duis ac nibh.', 39.928353, 116.416357, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (59, 'ipsum praesent blandit lacinia erat vestibulum', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 48.882433, -72.4404412, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (60, 'augue vel accumsan tellus nisi eu orci', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 42.048319, -8.4995497, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (61, 'sollicitudin mi sit amet lobortis sapien', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante.', 30.297685, 111.302191, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (62, 'morbi quis tortor id nulla ultrices aliquet', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 42.1119268, 44.9672863, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (63, 'nisl duis ac nibh fusce lacus', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', -9.8975064, -76.9398195, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (64, 'proin interdum mauris non ligula pellentesque ultrices', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', -19.8852788, -43.6644238, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (65, 'id consequat in consequat ut nulla sed accumsan', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 27.953479, 68.6224065, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (66, 'cras non velit nec nisi vulputate nonummy maecenas', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim.', -9.0202023, -78.6143377, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (67, 'ridiculus mus etiam vel augue', 'Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 34.5631817, -4.965185, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (68, 'dictumst etiam faucibus cursus urna ut tellus nulla', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 50.5860203, 27.6363775, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (69, 'proin eu mi nulla ac enim in tempor', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 12.6703542, 123.8732551, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (70, 'diam neque vestibulum eget vulputate ut ultrices vel', 'Integer a nibh.', 35.580629, 104.610668, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (71, 'in purus eu magna vulputate', 'Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 31.7640178, 54.578097, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (72, 'integer ac neque duis bibendum', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 40.233333, 22.3, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (73, 'congue elementum in hac habitasse platea dictumst morbi', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 13.7931278, 100.4993601, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (74, 'nulla quisque arcu libero rutrum ac lobortis vel', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.', 24.2521156, 120.7223572, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (75, 'id turpis integer aliquet massa id lobortis', 'Praesent blandit. Nam nulla.', -6.3270611, 106.1169299, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (76, 'morbi non lectus aliquam sit amet diam in', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', -6.8482297, 106.6802549, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (77, 'nulla eget eros elementum pellentesque quisque porta volutpat', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 23.124093, 113.8589235, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (78, 'vulputate vitae nisl aenean lectus pellentesque', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.', 63.0077349, 16.6652363, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (79, 'aenean fermentum donec ut mauris', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 37.810661, 120.758848, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (80, 'ante vivamus tortor duis mattis', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 4.7524091, -55.0272904, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (81, 'nunc proin at turpis a pede', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', -6.334, 105.9098, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (82, 'sapien quis libero nullam sit amet turpis', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 28.54, -81.38, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (83, 'in tempus sit amet sem fusce consequat nulla', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 9.8566537, 123.1426191, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (84, 'interdum in ante vestibulum ante ipsum', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.', 50.0843138, 12.4747444, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (85, 'accumsan tortor quis turpis sed ante vivamus', 'Ut at dolor quis odio consequat varius.', 14.6639812, 121.022408, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (86, 'nisi at nibh in hac habitasse platea', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 30.661419, 116.244678, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (87, 'sed augue aliquam erat volutpat in congue', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl.', 63.8223321, 20.2753893, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (88, 'ornare imperdiet sapien urna pretium nisl', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 55.6152783, 37.9416367, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (89, 'aenean fermentum donec ut mauris eget', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 43.6158396, 45.2369958, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (90, 'pharetra magna vestibulum aliquet ultrices erat tortor', 'Donec vitae nisi.', 10.142762, -85.454983, 'WAITING_APPROVAL');
insert into offer (id, title, description, latitude, longitude, status) values (91, 'donec semper sapien a libero nam', 'In eleifend quam a odio. In hac habitasse platea dictumst.', 49.4648362, 2.8898334, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (92, 'erat fermentum justo nec condimentum neque sapien', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 30.864884, 112.67271, 'REJECTED');
insert into offer (id, title, description, latitude, longitude, status) values (93, 'porta volutpat quam pede lobortis ligula sit', 'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', -7.0487503, 108.5314753, 'DELETED');
insert into offer (id, title, description, latitude, longitude, status) values (94, 'turpis donec posuere metus vitae ipsum aliquam', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', -6.8637417, 107.5902556, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (95, 'ultrices posuere cubilia curae nulla dapibus', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.', -7.3863388, 108.1888233, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (96, 'ornare consequat lectus in est', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.', 47.9527415, 21.6927245, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (97, 'id turpis integer aliquet massa id', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 38.290338, -8.2274142, 'MODIFICATIONS_NEEDED');
insert into offer (id, title, description, latitude, longitude, status) values (98, 'cum sociis natoque penatibus et magnis dis', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 27.100102, 68.3711064, 'DISABLED');
insert into offer (id, title, description, latitude, longitude, status) values (99, 'habitasse platea dictumst aliquam augue quam', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.', 6.8117856, 101.1843887, 'AVAILABLE');
insert into offer (id, title, description, latitude, longitude, status) values (100, 'lobortis vel dapibus at diam nam tristique tortor', 'Pellentesque at nulla.', 53.3656498, 34.1098425, 'DELETED');

`)
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
